spring:
  application:
    name: x-cloud-service-admin
  zipkin:
    base-url: http://127.0.0.1:9411
server:
  port: 8001
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
im:
  username: dev